[site]
title = "Ping-Jung(Lawrence) Lu"
description = "Master Student at NYU Electrical and Computer Engineering"
favicon = "/favicon.svg"
last_updated = "December 31, 2026"

[author]
name = "Ping-Jung(Lawrence) Lu"
title = "Master Student"
institution = "New York University"
avatar = "/awrence.JPG"

[social]
# Contact information (leave blank or delete to hide)

email = "pl2820@nyu.edu"
location = "New York City, New York"
location_url = "https://maps.google.com"
location_details = [
  "Room 123, Science Building,",
  "University Avenue, City, Country"
]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org"
github = "https://github.com/LawrenceLu0904"
linkedin = "https://www.linkedin.com/in/ping-jung-lu-9a6387239/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
